export interface JsToCSS {
  [key: string]: string;
}

export interface CSSToJS {
  [key: string]: string;
}

export interface Mapping {
  jsToCss: JsToCSS;
  cssToJs: CSSToJS;
}

const mapping = {
  jsToCss: {
    background: 'background',
    backgroundAttachment: 'background-attachment',
    backgroundColor: 'background-color',
    backgroundImage: 'background-image',
    backgroundPosition: 'background-position',
    backgroundRepeat: 'background-repeat',
    border: 'border',
    borderBottom: 'border-bottom',
    borderBottomColor: 'border-bottom-color',
    borderBottomStyle: 'border-bottom-style',
    borderBottomWidth: 'border-bottom-width',
    borderColor: 'border-color',
    borderLeft: 'border-left',
    borderLeftColor: 'border-left-color',
    borderLeftStyle: 'border-left-style',
    borderLeftWidth: 'border-left-width',
    borderRadius: 'border-radius',
    borderRight: 'border-right',
    borderRightColor: 'border-right-color',
    borderRightStyle: 'border-right-style',
    borderRightWidth: 'border-right-width',
    borderStyle: 'border-style',
    borderTop: 'border-top',
    borderTopColor: 'border-top-color',
    borderTopStyle: 'border-top-style',
    borderTopWidth: 'border-top-width',
    borderWidth: 'border-width',
    clear: 'clear',
    clip: 'clip',
    color: 'color',
    cssFloat: 'float',
    cursor: 'cursor',
    display: 'display',
    filter: 'filter',
    font: 'font',
    fontFamily: 'font-family',
    fontSize: 'font-size',
    fontVariant: 'font-variant',
    fontWeight: 'font-weight',
    height: 'height',
    left: 'left',
    letterSpacing: 'letter-spacing',
    lineHeight: 'line-height',
    listStyle: 'list-style',
    listStyleImage: 'list-style-image',
    listStylePosition: 'list-style-position',
    listStyleType: 'list-style-type',
    margin: 'margin',
    marginBottom: 'margin-bottom',
    marginLeft: 'margin-left',
    marginRight: 'margin-right',
    marginTop: 'margin-top',
    overflow: 'overflow',
    padding: 'padding',
    paddingBottom: 'padding-bottom',
    paddingLeft: 'padding-left',
    paddingRight: 'padding-right',
    paddingTop: 'padding-top',
    pageBreakAfter: 'page-break-after',
    pageBreakBefore: 'page-break-before',
    position: 'position',
    strokeDasharray: 'stroke-dasharray',
    strokeDashoffset: 'stroke-dashoffset',
    strokeWidth: 'stroke-width',
    textAlign: 'text-align',
    textDecoration: 'text-decoration',
    textIndent: 'text-indent',
    textTransform: 'text-transform',
    top: 'top',
    transition: 'transition',
    verticalAlign: 'vertical-align',
    visibility: 'visibility',
    width: 'width',
    zIndex: 'z-index'
  },
  cssToJs: {
    'background-attachment': 'backgroundAttachment',
    'background-color': 'backgroundColor',
    'background-image': 'backgroundImage',
    'background-position': 'backgroundPosition',
    'background-repeat': 'backgroundRepeat',
    'border-bottom-color': 'borderBottomColor',
    'border-bottom-style': 'borderBottomStyle',
    'border-bottom-width': 'borderBottomWidth',
    'border-bottom': 'borderBottom',
    'border-color': 'borderColor',
    'border-left-color': 'borderLeftColor',
    'border-left-style': 'borderLeftStyle',
    'border-left-width': 'borderLeftWidth',
    'border-left': 'borderLeft',
    'border-radius': 'borderRadius',
    'border-right-color': 'borderRightColor',
    'border-right-style': 'borderRightStyle',
    'border-right-width': 'borderRightWidth',
    'border-right': 'borderRight',
    'border-style': 'borderStyle',
    'border-top-color': 'borderTopColor',
    'border-top-style': 'borderTopStyle',
    'border-top-width': 'borderTopWidth',
    'border-top': 'borderTop',
    'border-width': 'borderWidth',
    'font-family': 'fontFamily',
    'font-size': 'fontSize',
    'font-variant': 'fontVariant',
    'font-weight': 'fontWeight',
    'letter-spacing': 'letterSpacing',
    'line-height': 'lineHeight',
    'list-style-image': 'listStyleImage',
    'list-style-position': 'listStylePosition',
    'list-style-type': 'listStyleType',
    'list-style': 'listStyle',
    'margin-bottom': 'marginBottom',
    'margin-left': 'marginLeft',
    'margin-right': 'marginRight',
    'margin-top': 'marginTop',
    'padding-bottom': 'paddingBottom',
    'padding-left': 'paddingLeft',
    'padding-right': 'paddingRight',
    'padding-top': 'paddingTop',
    'page-break-after': 'pageBreakAfter',
    'page-break-before': 'pageBreakBefore',
    'stroke-dasharray': 'strokeDasharray',
    'stroke-dashoffset': 'strokeDashoffset',
    'stroke-width': 'strokeWidth',
    'text-align': 'textAlign',
    'text-decoration': 'textDecoration',
    'text-indent': 'textIndent',
    'text-transform': 'textTransform',
    'vertical-align': 'verticalAlign',
    'z-index': 'zIndex',
    background: 'background',
    border: 'border',
    clear: 'clear',
    clip: 'clip',
    color: 'color',
    cursor: 'cursor',
    display: 'display',
    filter: 'filter',
    float: 'cssFloat',
    font: 'font',
    height: 'height',
    left: 'left',
    margin: 'margin',
    overflow: 'overflow',
    padding: 'padding',
    position: 'position',
    top: 'top',
    transition: 'transition',
    visibility: 'visibility',
    width: 'width'
  }
};

export default mapping;
